services:
  php:
    container_name: php_apache
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: yiisoftware/yii2-php:7.4-apache
    restart: always
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy      

  db:
    container_name: mysql8
    image: mysql:8.0.13
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: yii2basic
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_ROOT_AUTHENTICATION_METHOD: caching_sha2_password
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3305:3305' #05 para evitar porta padrão e dar confusão
    volumes:
      #- db_data:/var/lib/mysql
      - ./mysql:/var/lib/mysql:rw
      - ./docker/sql/create.sql:/docker-entrypoint-initdb.d/create.sql:ro
      - ./docker/sql/insert.sql:/docker-entrypoint-initdb.d/insert.sql:ro
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      # timeout: 10s
      # retries: 10
      test: mysqladmin ping -h 127.0.0.1 -u root --password=s3cr3t
      interval: 5s
      retries: 5
      timeout: 3s

  db_admin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost:8001/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_phpmyadmin_data:/var/www/html

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_adminer_data:/var/www/html

volumes:
  db_data:
  db_phpmyadmin_data:
  db_adminer_data:      